FROM adoptopenjdk/openjdk11
LABEL maintainer="Kevein Liu<kevein@flomesh.cn>"

ENV SERVER_LISTEN_PORT=9898

COPY server/target/server-0.0.2.jar /server-0.0.2.jar

COPY docker-entrypoint-server.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["docker-run", "server"]

STOPSIGNAL SIGQUIT

