FROM adoptopenjdk/openjdk11
LABEL maintainer="Kevein Liu<kevein@flomesh.cn>"

ENV CLIENT_LISTEN_PORT=8080

COPY client/target/client-0.0.2.jar /client-0.0.2.jar

COPY docker-entrypoint-client.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["docker-run", "client"]

STOPSIGNAL SIGQUIT

